### PR TITLE
fix: coins not deducted

### LINKED ISSUE #40: [Bug]: Money isn't deducted when transferred
### Detailed Description

I found this error in this project where

image

### Expected Behavior

-

### Current Behavior

-

### How can someone reproduce the behavior?

-

### What was you environment (os, browser, runtime, etc)?

Ubuntu Latest, Chrome Latest, Node14...

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by krshdev**
## Description

- [x] I have followed the [code of conduct](https://github.com/Alphasians/AINA/blob/main/contributing.md)
- [x] I have followed the [contributing guidelines](https://github.com/Alphasians/AINA/blob/main/contributing.md).
- [x] Either I have tested the code or my changes are not related to code.

## Related Issue

fixes #40 (RE)

### CODE REVIEW

File: src/commands/currency/transfer.js [hunk 1]
```diff
@@ -33,11 +33,12 @@ module.exports = class Economy extends Command {
    const recipient = await mongoCurrency.findUser(member.id, message.guild.id);
    const amt = args.amount;
 
-   if (user.coinsInWallet > amt){
+   if (user.coinsInWallet >= amt){
       await mongoCurrency.giveCoins(member.id, message.guild.id, amt );
+      await mongoCurrency.takeCoins(message.member.id, message.guild.id, amt);
```
Comment (Sonichigo) [inline src/commands/currency/transfer.js:38]: take coin is not a function in current package!

**Review by Sonichigo — CHANGES_REQUESTED** [review]

File: src/commands/currency/transfer.js (hunk 1 above)
Comment (krshdev) [inline src/commands/currency/transfer.js:38]:
```suggestion
      await mongoCurrency.deductCoins(message.member.id, message.guild.id, amt);
```

Comment (krshdev) [reply src/commands/currency/transfer.js:38]: ah yes, it is deductCoins

**Review by Sonichigo — APPROVED** [review]
